version: '3.4'

services:
  hugo:
    image: dgageot/build-step-hugo
    build:
      context: .
      dockerfile: Dockerfile.hugo
  firebase:
    image: dgageot/build-step-firebase
    build:
      context: .
      dockerfile: Dockerfile.firebase
